default_platform(:ios)

platform :ios do
  desc "Generates screenshots and uploads them to the App Store"
  lane :screenshots do
    capture_screenshots
    frame_screenshots
    upload_to_app_store(
      skip_binary_upload: true,
      skip_metadata: true,
      skip_app_version_update: true
    )
  end

  desc "Runs tests"
  lane :test do
    run_tests(scheme: "MetroBuddy")
  end

  desc "Push a new release build to the App Store"
  lane :release do
    set_xcconfig_value(
        path: "Configs/Base.xcconfig",
        name: "CURRENT_PROJECT_VERSION",
        value: ENV['BUILD_NUMBER']
    )

    set_xcconfig_value(
        path: "Configs/Base.xcconfig",
        name: "SHORT_VERSION_STRING",
        value: ENV['APP_VERSION']
    )

    build_app(scheme: "MetroBuddy")
    upload_to_app_store(skip_metadata: true)
  end
end
