name: CI
env:
  DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    # 1) Check out the repository
    - name: Clone Repository
      uses: actions/checkout@v2

    # 2) Install dependencies
    - name: Install Dependencies
      run: bundle install

    # 3) Set up Code Signing
    - name: Set Up Code Signing
      run: bundle exec fastlane run setup_ci

    # 4) Build and test the app
    - name: Run Tests
      run: bundle exec fastlane test
