name: CI
env:
  DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Debug Action
      run: cat "$GITHUB_EVENT_PATH" | jq -M .

    # 1) Check out the repository
    - name: Clone Repository
      uses: actions/checkout@v2

    # 2) Install dependencies
    - name: Install Dependencies
      run: bundle install

    # 3) Build and test the app
    - name: Run Tests
      run: bundle exec fastlane test
