name: Release

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build Number'
        required: true
      app_version:
        description: 'App Version'
        required: true
      branch:
        description: 'Branch'
        default: 'main'
        required: true

jobs:
  release:
    runs-on: macos-10.15

    steps:
    # 1) Clone the Repository
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: ${{ github.event.inputs.branch }}

    # 2) Set Environment
    - name: Set Environment
      run: export BUILD_NUMBER="${{ github.event.inputs.build_number }}" |
        export APP_VERSION="${{ github.event.inputs.app_version }}

    # 3) Build and Upload the App
    - name: Create Release Build
      run: bundle exec fastlane release

    # 4) Commit Version Bump and Create Tag
    - name: Bump Version
      run: git commit -m 'Version Bump' ./Configs/Base.xcconfig |
        git tag $APP_VERSION-build.$BUILD_NUMBER |
        git push && git push --tags

    # 5) Create Release
    - name: Create Release
      uses: actions/create-release@v1.1.3
      with:
        tag_name: $APP_VERSION-build.$BUILD_NUMBER
